### PR TITLE
OU-283: allow dev console to add more namespaces to the default selection

### PR DESCRIPTION
**Pull request by jgbernalp**
This PR adds the namespace filter to the dev console logs. This will allow users to select multiple namespaces in a single query, the default namespace selection is based on the dev console dropdown.

https://github.com/openshift/logging-view-plugin/assets/5461414/1f170826-a849-475c-8922-58517f3c215e

### CODE REVIEW

**Comment by fkargbo** [comment]
Hi @jgbernalp I reviewed the attached video. The implementation looks good to me! I have two comments:

1. Regarding the "Project" selector/filter; if Projects and Namespaces mean the same thing on OCP, we are repeating the same filtering functionality twice. First in the top left corner (main Project selector dropdown) and second at the top of the table, right below the query input. Could this be a workaround for us to control the ability for multiple selections of Namespaces?
2. Regarding the inline validation when the query doesn't have a namespace input - I've attached an image showing the PatternFly recommendation for presenting input field validations in these instances.
image (1) 1

Let me know if you have any questions.

Thanks!

**Comment by jgbernalp** [comment]
@fkargbo indeed the double selection is a workaround as we don't control the dropdown in this view. Is part of the console and not the plugin. But this will allow to select other namespaces than the current project.

Thnx for the comment on the inline error. Do you have a suggestion when the query input is not there? this is the default as not all the time the query is shown.

**Comment by jgbernalp** [comment]
> Why is this feature not leveraging the `/api/logs/v1/<tenant>/loki/api/v1/label/kubernetes_namespace_name/values` API call? Asking Loki for the user's available values ensures that we run through the same access review code paths as the query path.

@periklis will this return values for the namespaces that the user has access to but have no logs yet? trying to decide if it will be better just to show on the list the allowed namespaces or the allowed namespaces that have logs. Is it a common case that this label wont for namespaces that the user has access to?

**Comment by periklis** [comment]
> > Why is this feature not leveraging the `/api/logs/v1/<tenant>/loki/api/v1/label/kubernetes_namespace_name/values` API call? Asking Loki for the user's available values ensures that we run through the same access review code paths as the query path.
> 
> @periklis will this return values for the namespaces that the user has access to but have no logs yet? trying to decide if it will be better just to show on the list the allowed namespaces or the allowed namespaces that have logs. Is it a common case that this label wont for namespaces that the user has access to?

This is a good argument you are raising. Loki's Label values API will return only label values for existing logs. Thus I am asking what is the value showing namespaces w/o logs yet?

**Comment by jgbernalp** [comment]
> > > Why is this feature not leveraging the `/api/logs/v1/<tenant>/loki/api/v1/label/kubernetes_namespace_name/values` API call? Asking Loki for the user's available values ensures that we run through the same access review code paths as the query path.
> > 
> > 
> > @periklis will this return values for the namespaces that the user has access to but have no logs yet? trying to decide if it will be better just to show on the list the allowed namespaces or the allowed namespaces that have logs. Is it a common case that this label wont for namespaces that the user has access to?
> 
> This is a good argument you are raising. Loki's Label values API will return only label values for existing logs. Thus I am asking what is the value showing namespaces w/o logs yet?

could It be that the workloads in the namespace are not producing logs or a log collection error? If this not a common case and log collection errors can be checked elsewhere there won't be additional value

**Comment by fkargbo** [comment]
@jgbernalp 
> Thnx for the comment on the inline error. Do you have a suggestion when the query input is not there? this is the default as not all the time the query is shown.

If I understood you correctly, you're referring to a use case when the query input field is empty...
In this case, we wouldn't need any validation - we could have some standard placeholder text in the input field such as "Enter your namespace query here" or "an example of a query syntax" which will disappear when the user starts typing.

Alternatively, we could have a helper text with a query example underneath the input field.

I've attached an image with PatternFly examples;

1. Standard helper text
2. Placeholder text

Hope I understood your question. :)

**Comment by jgbernalp** [comment]
@fkargbo I adjusted the input validation UX as shown in the video below:

https://github.com/openshift/logging-view-plugin/assets/5461414/0519ca97-beb5-4c32-96a1-7ab87e66d5de

**Comment by fkargbo** [comment]
> @fkargbo I adjusted the input validation UX as shown in the video below:
> 
>  Screen.Recording.2024-01-23.at.09.20.51.mov

Looks good!

**Pull request merged**
