### PR TITLE
Use backend date sorting for consistent table results

### PR DESCRIPTION
**Pull request by jgbernalp**
Fixes: https://issues.redhat.com/browse/OU-123
Related case: https://issues.redhat.com/browse/LOG-3322

### CODE REVIEW

**Comment by periklis** [comment]
@jgbernalp Is this still using the limit of 100 entries? (https://grafana.com/docs/loki/latest/api/#query-loki-over-a-range-of-time)

**Comment by jgbernalp** [comment]
@periklis yes, the limit is kept. This PR sends the `direction` param to Loki. So even in the case of 100 initial entries limit, the sorting is what the user expects based on the selected time range. If I'm not mistaken the issue was not the limit itself but a combination of the limit with the sorting. Fixes the sorting the limit still applies.

**Comment by periklis** [comment]
> @periklis yes, the limit is kept. This PR sends the `direction` param to Loki. So even in the case of 100 initial entries limit, the sorting is what the user expects based on the selected time range. If I'm not mistaken the issue was not the limit itself but a combination of the limit with the sorting.

Yes you are correct the issue was the combination of those two. I was asking out of curiousity if we exposed the `limit` configuration to the user anyhow.

**Comment by jgbernalp** [comment]
@periklis  A new task was created to address this: https://issues.redhat.com/browse/OU-128

**Review by periklis — APPROVED** [review]

**Pull request merged**
