### PR TITLE
OU-539: Dynamically Reload Certificates

### PR DESCRIPTION
**Pull request by zhuje**
### JIRA
https://issues.redhat.com/browse/OU-576

### Related Issues
Based on modifications from monitoring-plugin: https://github.com/openshift/monitoring-plugin/pull/264

QE subtask:
https://issues.redhat.com/browse/OU-576

### Demo
https://drive.google.com/file/d/15yfDqW4Nt_8IyN8BiX-lmhffeph-6Tln/view?usp=sharing
Figure 1. Video demo (~3 min). Shows TLS certificates being dynamically reloaded. Shows logging-view-plugin pod logs that describe the reason for reloading and shows new certificate present in a pod using openssl s_client.

/hold
For QE testing

### CODE REVIEW

**Comment by zhuje** [comment]
/hold 

/cc @anpingli 
This PR is trying to address [OU-575](https://issues.redhat.com/browse/OU-575). Could you test it?

**Review by Elno5 — APPROVED** [review]

**Comment by zhuje** [comment]
/cc @anpingli 

I pushed some changes, could you test this PR?

**Review by Elno5 — APPROVED** [review]

**Review by Elno5 — APPROVED** [review]

**Comment by anpingli** [comment]
The fix works well. We can merge it.

**Pull request merged**
